name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Manual trigger event

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: labhkari
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies (Backend)
        run: |
          cd server
          npm install

      - name: Install dependencies (Frontend)
        run: |
          cd client
          npm install

      - name: Build backend
        run: |
          cd server
          npm run build

      - name: Build frontend
        run: |
          cd client
          npm run build

      - name: Build Docker images
        run: |
          docker build -t my-app-backend ./server
          docker build -t my-app-frontend ./client

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Verify services are running
        run: docker ps
